### ISSUE TITLE
CI failure since prost 0.11 upgrade

### ISSUE THREAD

**Issue by shikhar** [mechiru/google-api-proto#5]
Thanks for merging https://github.com/mechiru/google-api-proto/pull/3 @mechiru!

Unfortunately it looks like CI is failing now because [protobuf](https://packages.ubuntu.com/search?searchon=sourcenames&keywords=protobuf) is not installed on the Ubuntu image. I did not notice this because locally I did have `protoc` available.

See https://github.com/tokio-rs/prost/releases/tag/v0.11.0
> prost-build now requires protoc to be available in the path or set via the PROTOC env var.

Options:
- install [protobuf](https://packages.ubuntu.com/search?searchon=sourcenames&keywords=protobuf) on the image CI runs
- use [protobuf-src](https://docs.rs/prost-build/latest/prost_build/#sourcing-protoc) to build from source and set `PROTOC` accordingly

**Comment by mechiru** [comment]
@shikhar Thank you reporting it. I fixed this issue!
